param(
    [string]$Source = (Join-Path $PSScriptRoot '..\GRAPHACLYSM_성좌_240노드.json'),
    [string]$Destination = (Join-Path $PSScriptRoot '..\Assets\Scripts\Core\Runs\GrowthCatalog.Generated.cs')
)

$ErrorActionPreference = 'Stop'
$catalog = Get-Content -Raw -LiteralPath $Source -Encoding UTF8 | ConvertFrom-Json

if ($catalog.nodes.Count -ne 240) {
    throw "Expected 240 nodes, found $($catalog.nodes.Count)."
}

$prototypeIds = @{
    'ian.triple.form' = $true
    'ian.execute.form' = $true
    'ian.exchange.form' = $true
    'ian.u.collapse.form' = $true
    'ian.u.immortal.form' = $true
    'ian.u.invert.form' = $true
    'luna.fulljump.form' = $true
    'luna.return.form' = $true
    'luna.chain.form' = $true
    'luna.u.embrace.form' = $true
    'luna.u.blade.form' = $true
    'luna.u.stop.form' = $true
}

function Escape-CSharp([string]$value) {
    if ($null -eq $value) { return '' }
    return $value.Replace('\', '\\').Replace('"', '\"').Replace("`r", '').Replace("`n", '\n')
}

function String-Array($values) {
    $items = @($values)
    if ($items.Count -eq 0) { return 'System.Array.Empty<string>()' }
    return 'new[] { ' + (($items | ForEach-Object { '"' + (Escape-CSharp ([string]$_)) + '"' }) -join ', ') + ' }'
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('namespace Graphaclysm.Core.Runs')
$lines.Add('{')
$lines.Add('    public static partial class GrowthCatalog')
$lines.Add('    {')
$lines.Add('        private static GrowthNodeDefinition[] CreateDefinitions()')
$lines.Add('        {')
$lines.Add('            return new[]')
$lines.Add('            {')

foreach ($node in $catalog.nodes) {
    $owner = if ($node.owner -eq '공통') { 'Common' } elseif ($node.owner -eq '루나') { 'Luna' } else { 'Ian' }
    $minimumCount = if ($null -ne $node.requires_at_least) { [int]$node.requires_at_least.count } else { 0 }
    $minimumNodes = if ($null -ne $node.requires_at_least) { String-Array $node.requires_at_least.nodes } else { 'System.Array.Empty<string>()' }
    $status = if ($prototypeIds.ContainsKey([string]$node.id)) { 'PrototypePartial' } else { 'Planned' }
    $equipLimit = if ($null -ne $node.equip_limit) { [int]$node.equip_limit } else { 0 }
    $line = '                new GrowthNodeDefinition("{0}", GrowthOwner.{1}, "{2}", "{3}", "{4}", "{5}", {6}, "{7}", "{8}", "{9}", "{10}", "{11}", {12}, {13}, {14}, {15}, GrowthImplementationStatus.{16}),' -f `
        (Escape-CSharp ([string]$node.id)), $owner, (Escape-CSharp ([string]$node.section)), `
        (Escape-CSharp ([string]$node.name)), (Escape-CSharp ([string]$node.effect)), (Escape-CSharp ([string]$node.drawback)), `
        [int]$node.cost, (Escape-CSharp ([string]$node.kind)), (Escape-CSharp ([string]$node.slot)), `
        (Escape-CSharp ([string]$node.family)), (Escape-CSharp ([string]$node.exclusive_group)), `
        (Escape-CSharp ([string]$node.equip_limit_group)), $equipLimit, (String-Array $node.requires_all), `
        $minimumCount, $minimumNodes, $status
    $lines.Add($line)
}

$lines.Add('            };')
$lines.Add('        }')
$lines.Add('    }')
$lines.Add('}')

[System.IO.File]::WriteAllLines((Resolve-Path (Split-Path -Parent $Destination)).Path + '\' + (Split-Path -Leaf $Destination), $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated $Destination from $Source"
